
name: Deploy React Application to Github Pages
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# By default only runs on pushes on the master
description: Build and deploy your React website via Github Pages  
author: joshuanoronha
branding: 
  color: yellow
  icon: arrow-up
on:
  push:
    branches: [ master ] # You can add branches here
  # pull_request:
  #   branches: [ master ] # You can add branches here
  jobs:
  build:
    # System to run on
    runs-on: ubuntu-latest

    # Steps for deployment
    steps:
    - uses: actions/checkout@v2
    # Setup node environment
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        # Select node version
        node-version: '10.x' 

    # Run npm i to get dev dependencies
    - name: Run npm install
      run: npm install
    
    # Step to Build code 
    - name: Build Code
      run: npm run-script build

    # Step to deploy code
    - name: Deploy  
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        # For authentication via github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Change target branch 
        BRANCH: gh-pages 
        # Folder where the code is built
        FOLDER: build